//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladisteDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roba()
        {
            this.RobaNaLokacijis = new HashSet<RobaNaLokaciji>();
            this.StavkeDokumentas = new HashSet<StavkeDokumenta>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MjernaJedinica { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual MjernaJedinica MjernaJedinica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RobaNaLokaciji> RobaNaLokacijis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkeDokumenta> StavkeDokumentas { get; set; }
    }
}
