//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladisteDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladisteDatabase : DbContext
    {
        public SkladisteDatabase()
            : base("name=SkladisteDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dokument> Dokuments { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Lokacija> Lokacijas { get; set; }
        public virtual DbSet<MjernaJedinica> MjernaJedinicas { get; set; }
        public virtual DbSet<Roba> Robas { get; set; }
        public virtual DbSet<RobaNaLokaciji> RobaNaLokacijis { get; set; }
        public virtual DbSet<StavkeDokumenta> StavkeDokumentas { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
        public virtual DbSet<VrstaDokumenta> VrstaDokumentas { get; set; }
    }
}
